<a href="https://colab.research.google.com/github/Ayushichadha/language_modelling/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Introduction to tensors**

Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data. Tensors are also optimized for automatic differentiation.

In [6]:
import torch
import numpy as np

In [5]:
# initialising a tensor
# 1. directly from data
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [7]:
#2. from numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

From another tensor:

The new tensor retains the properties(shape, datatype) of the argument tensor, unless explicitly overridden.

In [8]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f'Ones tensor: \n {x_ones}\n')

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f'Random tensor: \n {x_rand}\n')

Ones tensor: 
 tensor([[1, 1],
        [1, 1]])

Random tensor: 
 tensor([[0.7576, 0.2793],
        [0.4031, 0.7347]])



With random or constant values:
'shape' is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

In [12]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor: \n {rand_tensor} \n')
print(f'Ones Tensor: \n {ones_tensor} \n')
print(f'Zeros Tensor: \n {zeros_tensor}')

Random Tensor: 
 tensor([[0.4162, 0.2843, 0.3398],
        [0.5239, 0.7981, 0.7718]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


Attributes of a Tensor: Tensor attributes their shape, datatype, and the device on which they are stored.

In [13]:
tensor = torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


**Operations on Tensors**:



Note (from Pytorch tut):

(over 1200 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling and more.)

Each of these operations can be run on the CPU and Accelerator such as CUDA, MPS, MTIA, or XPU. If you’re using Colab, allocate an accelerator by going to Runtime > Change runtime type > GPU.

By default, tensors are created on the CPU. We need to explicitly move tensors to the accelerator using .to method (after checking for accelerator availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [14]:
# We move our tensor to the current accelerator if available
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

Standard numpy-like indexing and slicing:

In [15]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


joining tensors

In [17]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
print(t1.shape)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
torch.Size([4, 12])


Arithmetic operations

In [18]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

------------[Another tutorial from Pytorch]-----------

In [1]:
import torch
torch.manual_seed(1)

Creating Tensors

Tensors can be created from Python lists with the torch.tensor() function

In [3]:
V_data = [1., 2., 3.]
V = torch.tensor(V_data)
print(V)

# creates a matrix
M_data = [[1., 2., 3.], [4., 5., 6.]]
M = torch.tensor(M_data)
print(M)

# creates a 3D tensor of size 2x2X2.
T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]

T = torch.tensor(T_data)
print(T)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


**What is a 3D tensor?**

 Think about it like this. If you have a vector, indexing into the vector gives you a scalar. If you have a matrix, indexing into the matrix gives you a vector. If you have a 3D tensor, then indexing into the tensor gives you a matrix!

In [19]:
# Index into V and get a scalar (0 dimensional tensor)
print(V[0])
# Get a Python number from it
print(V[0].item())

# Index into M and get a vector
print(M[0])

# Index into T and get a matrix
print(T[0])

tensor(1.)
1.0
tensor([1., 2., 3.])
tensor([[1., 2.],
        [3., 4.]])


In [20]:
# creating a tensor with random data and the supplied dimensionality with torch.randn()
x = torch.randn((3, 4, 5))
print(x)


tensor([[[ 0.9837,  0.8793, -1.4504, -1.1802,  0.4100],
         [ 0.4085,  0.2579,  1.0950,  1.3264,  0.8547],
         [-0.2805,  0.7000, -1.4567,  1.6089,  0.0938],
         [-1.2597, -0.5047, -1.4746, -0.3416, -0.3003]],

        [[ 1.3075, -1.1628,  0.1196, -0.1631, -0.9247],
         [-0.9301,  1.4301,  0.4208, -0.3538,  0.7639],
         [-0.5890, -0.7636,  0.6155,  0.1938, -2.5832],
         [ 0.8539,  1.2466,  0.5057,  0.9505,  1.2966]],

        [[-0.1010,  0.3434, -1.0703, -0.8743, -0.3030],
         [-1.7618,  0.6348, -0.8044, -1.0371, -1.0669],
         [-0.2085, -0.2155,  2.2952,  0.6749,  1.7133],
         [-1.7943, -1.5208,  0.9196, -0.5484, -0.3472]]])


In [21]:
# operations with tensors
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x + y
print(z)

tensor([5., 7., 9.])


In [22]:
# By default, it concatenates along the first axis (concatenates rows)
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.cat([x_1, y_1])
print(z_1)

# Concatenate columns:
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 5)
# second arg specifies which axis to concat along
z_2 = torch.cat([x_2, y_2], 1)
print(z_2)

# If your tensors are not compatible, torch will complain.  Uncomment to see the error
# torch.cat([x_1, x_2])

tensor([[-1.3459e+00,  5.1190e-01, -6.9328e-01, -1.6676e-01, -9.9988e-01],
        [-1.6476e+00,  8.0983e-01,  5.5424e-02,  1.1340e+00, -5.3264e-01],
        [ 6.5921e-01, -1.5964e+00, -3.7687e-01, -3.1020e+00, -9.9467e-02],
        [-7.2126e-01,  1.2708e+00, -2.0225e-03, -1.0952e+00,  6.0165e-01],
        [ 6.9841e-01, -8.0052e-01,  1.5381e+00,  1.4673e+00,  1.5951e+00]])
tensor([[-1.5279,  1.0156, -0.2020, -1.2960, -0.9434,  0.6684,  1.1628, -0.3229],
        [-1.2865,  0.8231, -0.6101,  1.8782, -0.5666,  0.4016, -0.1153,  0.3170]])


**Reshaping Tensors**

In [23]:
x = torch.randn(2, 3, 4)
print(x)
print(x.view(2, 12))  # Reshape to 2 rows, 12 columns
# Same as above.  If one of the dimensions is -1, its size can be inferred
print(x.view(2, -1))

tensor([[[ 2.6415, -0.9624, -0.2076, -1.3889],
         [ 0.0127, -1.8734,  1.7997,  0.2824],
         [-1.2560,  0.8956,  0.1675,  0.7514]],

        [[ 2.4142,  1.0206, -0.4405, -1.7342],
         [-1.2362,  1.5786, -1.1161,  0.7678],
         [-0.5882,  2.1189, -0.5422, -2.4593]]])
tensor([[ 2.6415, -0.9624, -0.2076, -1.3889,  0.0127, -1.8734,  1.7997,  0.2824,
         -1.2560,  0.8956,  0.1675,  0.7514],
        [ 2.4142,  1.0206, -0.4405, -1.7342, -1.2362,  1.5786, -1.1161,  0.7678,
         -0.5882,  2.1189, -0.5422, -2.4593]])
tensor([[ 2.6415, -0.9624, -0.2076, -1.3889,  0.0127, -1.8734,  1.7997,  0.2824,
         -1.2560,  0.8956,  0.1675,  0.7514],
        [ 2.4142,  1.0206, -0.4405, -1.7342, -1.2362,  1.5786, -1.1161,  0.7678,
         -0.5882,  2.1189, -0.5422, -2.4593]])
